-- Migration: Create Row Level Security (RLS) policies
-- These policies enforce user-level data access control

-- Enable RLS on all memory tables
ALTER TABLE agent_working_memory ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_chats ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist (for idempotency)
DROP POLICY IF EXISTS "Users can access their own working memory" ON agent_working_memory;
DROP POLICY IF EXISTS "Users can access their own messages" ON agent_messages;
DROP POLICY IF EXISTS "Users can access their own chats" ON agent_chats;

-- RLS Policy: Users can only access their own working memory
-- This policy ensures users can only read/write their own memory data
CREATE POLICY "Users can access their own working memory"
ON agent_working_memory
FOR ALL
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

-- RLS Policy: Users can only access their own messages
-- This policy ensures users can only read/write their own conversation history
CREATE POLICY "Users can access their own messages"
ON agent_messages
FOR ALL
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

-- RLS Policy: Users can only access their own chats
-- This policy ensures users can only read/write their own chat metadata
CREATE POLICY "Users can access their own chats"
ON agent_chats
FOR ALL
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

-- Note: auth.uid() returns the user ID from the JWT token's 'sub' field
-- The JWT is generated by generateSupabaseJWT() with feishuUserId as the 'sub' value

